version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/solidity-examples
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: npm install
          command: npm install
      - run:
          name: pull solc image
          command: 'docker pull ethereum/solc:stable'
      - run:
          name: pull testeth image
          command: 'docker pull holiman/testeth:latest'
      - run:
          name: test
          command: npm run testwithdocker
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml